remote_theme: just-the-docs/just-the-docs
logo: "/images/sfulogo.png"
footer_content: "Copyright &copy; 2022 SFU"



# Google Analytics Tracking (optional)
ga-tracking: G-ZDXPF7GDG7
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)



callouts:
  careful:
    title: Careful
    color: red

  important:
    title: Important
    color: purple

  tip:
    title: Tip
    color: yellow

  new:
    title: new
    color: green

