remote_theme: just-the-docs/just-the-docs
logo: "/images/sfulogo.png"
footer_content: "Copyright &copy; 2022 SFU"




callouts:
  careful:
    title: Careful
    color: red

  important:
    title: Important
    color: purple

  tip:
    title: Tip
    color: yellow

  new:
    title: new
    color: green

